run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor/
  skip-files:
    - \.pb\.go$

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/chetanyakan/realworld-go
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - path: util/util.go
      linters:
        - deadcode
        - unused
    - path: datastore/main.go
      linters:
        - deadcode
        - unused
    - path: _test\.go
      linters:
        - bodyclose
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
