# Continuous Integration Workflow to check pushes to master and pull requests:
# - code style guidelines are followed (make check-style)
# - tests pass (make test)
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    name: Check style; test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go v1.14.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: check style
        run: make check-style

      - name: run tests
        run: make test
